repeat: 1
problems:
  facility_location:
    size:
      - 8
    libraries:
      pyomo: 64
      gurobipy: 128
      cvxpy: 32
      jump: 256
      pyoframe: true
      pyoptinterface: true
  energy_planning:
    requires_inputs: true
    libraries:
      pyoframe: true
    size:
      - 2
      - 4
      - 24
      - 168
      # - 730
      # - 8670
  dummy_model:
    size:
      - 100

    libraries:
      pyomo: 1000
      gurobipy: 1000
      cvxpy: 1000
      jump: true
      pyoframe: true
      pyoptinterface: true
      linopy: 1000


solvers:
  - gurobi
  # - highs
  # - mosek

libraries:
  - pyoframe
  - pyomo
  - cvxpy
  - gurobipy
  - jump
  # - linopy
  - pyoptinterface
