# Note: we don't allow timeouts
name: test
save_outputs: true
julia_trace_compile: true
problems:
  facility_location:
    size: [2]
  facility_location_construct_only:
    size: [2]
    construct_only: true
  simple_problem:
    size: [100]
    inputs:
      - "input_100.parquet"
  energy_simple:
    code_dir: energy_planning
    inputs: "*"
    size: [2]
    args:
      security_constrained: false
      capacity_expansion: false
      yearly_limits: false
      variable_capacity_factors: false
    solver_args:
      Method: 2
      Crossover: false
  energy_all:
    code_dir: energy_planning
    inputs: "*"
    size: [1]

solvers:
  - gurobi
  # - highs
  # - mosek

libraries:
  - pyoframe
  - pyomo
  - cvxpy
  - gurobipy
  - jump
  - linopy
  - pyoptinterface
  - ampl