name: Benchmarks
on:
  # TODO remove pull_request once it's consistent.
  pull_request:
    branches: ["*"]
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * WED"  # Every Wed at 05:00

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
      - uses: julia-actions/cache@v3
        with:
          cache-name: julia-benchmarking-cache
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Setup optimizers
        uses: ./.github/actions/setup_optimizers_linux
        with:
          GUROBI_WLS: ${{ secrets.GUROBI_WLS }}
      # Should not be necessary since we shouldn't recompute input files!
      # - name: Install scikit-sparse dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libsuitesparse-dev
      - name: Install dependencies
        run: |
          pip install -e .
          cd benchmarks
          pip install -e .
      - name: Install and test AMPL
        run: |
          python -m amplpy.modules install gurobi --upgrade
          python -m amplpy.modules activate ${{ secrets.AMPL_LICENSE_UUID }}
          python -c "from amplpy import AMPL; model = AMPL()"
      - name: Install Julia packages
        run: |
          julia --project=benchmarks -e 'using Pkg; Pkg.instantiate()'
      - name: Touch inputs to not regenerate
        run: |
          cd benchmarks/src/energy_planning
          snakemake --touch ./model_data/
      - name: Run benchmarks
        run: |
          python benchmarks/test.py --fail-on-error
