name: Black and isort

on: [pull_request]

env:
  INPUT_JUPYTER: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: isort/isort-action@v1