# Note: We use the insecure pull_request_target to allow running workflows from forks.
# However, we've added checks (see below) for safety.
# In short, the 'safe to test' label must exist AND the workflow must be run by someone with write access.
# See more details here:
#   - https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
#   - https://michaelheap.com/access-secrets-from-forks/
name: Tests
on:
  pull_request_target:
    branches: [ '*' ]
  workflow_dispatch:
jobs:
  run_safety_checks:
    if: github.event.pull_request.head.repo.full_name != github.repository
      # Important checks to ensure that the user has the required permissions. See note above.
      # Step 1: If user has current permissions we're good!
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Otherwise, get triggering user's permissions
      - name: Get Triggering User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        id: checkTriggeringAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # If neither has permissions and no 'safe to test' label throw error
      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false' && steps.checkTriggeringAccess.outputs.require-result == 'false' && !contains(github.event.pull_request.labels.*.name, 'safe to test')
        shell: bash
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Re-run the test yourself if you have write permissions. Alternatively, add the label 'safe to test' to the PR to give the user write permissions (only if you trust them)."
          exit 1
  run:
    needs: run_safety_checks
    uses: ./.github/workflows/ci.yml
    with:
      pr_ref: ${{ github.event.pull_request.head.sha }}
    secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        GUROBI_WLS: ${{ secrets.GUROBI_WLS }}