# This workflow ensures that `ruff format` passes on pull requests.
name: Check linting with Ruff
on: [pull_request]

env:
  INPUT_JUPYTER: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3  # Default is linter
      
